//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPrison.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detainees
    {
        public int IdDetainee { get; set; }
        public Nullable<int> PassSeries { get; set; }
        public int PassNumber { get; set; }
        public string SurName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string BirthDay { get; set; }
        public string BirthLocation { get; set; }
        public string CurrLocation { get; set; }
        public string PhoneNumber { get; set; }
        public string Work { get; set; }
        public string WorkPhone { get; set; }
        public string School { get; set; }
    }
}
