//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPrison.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detentions
    {
        public int IdDetention { get; set; }
        public Nullable<int> IdDetainee { get; set; }
        public Nullable<System.DateTime> Detaintime { get; set; }
        public string Reason { get; set; }
        public Nullable<int> IdReport { get; set; }
        public Nullable<System.DateTime> ReleaseTime { get; set; }
    }
}
