//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPrison.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hearings
    {
        public int IdHearing { get; set; }
        public string Office { get; set; }
        public string Decision { get; set; }
        public string Punishment { get; set; }
        public Nullable<int> IdJudge { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> IdReport { get; set; }
    }
}
