//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPrison.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JailDB : DbContext
    {
        public JailDB()
            : base("name=JailDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompelLocations> CompelLocations { get; set; }
        public virtual DbSet<Courts> Courts { get; set; }
        public virtual DbSet<Detainees> Detainees { get; set; }
        public virtual DbSet<Detentions> Detentions { get; set; }
        public virtual DbSet<Hearings> Hearings { get; set; }
        public virtual DbSet<Judges> Judges { get; set; }
        public virtual DbSet<Officers> Officers { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<Notice> Notice { get; set; }
    }
}
