//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPrison.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int IdReport { get; set; }
        public string Section { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> IdOfficer { get; set; }
        public bool Notification { get; set; }
        public Nullable<int> IdLocation { get; set; }
    }
}
